### ISSUE TITLE
package-boot-aoi fails to run

### ISSUE THREAD

**Issue by sean-foley** [PhilippHeuer/camunda-template#1]
First, I am want to thank you for putting together this Camunda template.  It has saved me a bunch of time working through the boilerplate. 
 
When I run the camunda-template-package-boot-aio (the bootRunAllInOneWithLocalDb task), the process fails to load because of some wireup/missing EnableWebMvcConfiguration.class not found.  If I comment out line 16 of corresponding subproject's build.gradle file ( compile group:'org.camunda.bpm.springboot', name: 'camunda-bpm-spring-boot-starter-webapp'), then the process will load, but without any Camunda web support.

Since Spring is still new to me, I'm not sure if this is a Camunda issue or not?  When you built/ran your template, did you have this problem?  Any assistance would be appreciated.

The console ouput (snippet)
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
14:00:23.677 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/web/bind/MissingMatrixVariableException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
	at org.camunda.bpm.CamundaProcessApplication.main(CamundaProcessApplication.java:60)
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/bind/MissingMatrixVariableException
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.getDefaultArgumentResolvers(RequestMappingHandlerAdapter.java:649)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.afterPropertiesSet(RequestMappingHandlerAdapter.java:565)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
	... 16 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.web.bind.MissingMatrixVariableException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 common frames omitted

> Task :camunda-template-package-boot-aio:bootRun FAILED

FAILURE: Build failed with an exception.

**Comment by sean-foley** [comment]
After a few hours of google-fu, I stumbled on the following: https://stackoverflow.com/questions/38145024/error-creating-bean-with-name-requestmappinghandleradapter

The parent build.gradle file line 37 puts a dependency on dependency group: 'org.springframework', name: 'spring-webmvc', version: '5.1.0.RELEASE'.  I commented out this line, rebuilt the project, and did a debug run of the bootRunAllInOneWithLocalDb task.  The process did not fail, and I could successfully load the Camunda web app page via http://localhost:8080/

Removing the dependency on the spring mvc seems to do the trick.

**Comment by PhilippHeuer** [comment]
Hi, thanks a lot for creating the issue and providing info about the cause 👍 

You'r right about that, but i only defined that version because it was needed for war deployments, not for the in memory spring boot execution.
By removing that you have have most likely broken the war deployment - i will take a look later and make sure its working with both war and in memory again before i commit the changes.

I really wonder how this happend though because it was working previously.

**Comment by sean-foley** [comment]
I pulled your latest commits down and tested the AIO build.  I can confirm that the Camunda web support now works.  Nice work and thanks again!
